query AllProducts($locale: LocaleInputType!) {
  Products(locale: $locale, limit: 10000) {
    docs {
      id
      title
      slug
      priceInEUR
      inventory
      enableVariants
      description
      gallery {
        id
        url
        thumbnailURL
        width
        height
        alt
      }
      variants {
        docs {
          id
          priceInEUR
          title
          priceInEUR
        }
      }
      variantTypes {
        id
        label
        name
        options {
          docs {
            id
            label
            value
          }
        }
      }

      categories {
        id
        slug
        title
      }

      meta{
        title
        description
      }
    }

    totalDocs
  }
}
