query Categories($locale: LocaleInputType!) {
  Categories(locale: $locale) {
    docs {
      id
      title
      slug
      description
      image {
        id
        alt
        url
        filename
        width
        height
        sizes {
          categoryPreview {
            url
            width
            height
            mimeType
            filename
          }
        }
      }
      meta {
        title
        description
      }
    }
  }
}
