query InformationBanner($locale: LocaleInputType!) {
  InformationBanner(locale: $locale) {
    items {
      text
      icon {
        id
        ... on SvgMedia {
          id
          svgContent
        }
      }
    }
  }
}
