query ProductById($id: Int!, $locale: LocaleInputType!) {
  Products(where: { id: { equals: $id } }, locale: $locale, limit: 1) {
    docs {
      id
      title
      slug
      priceInEUR
      enableVariants
      description
      inventory
      gallery {
        id
        url
        thumbnailURL
        width
        height
        alt
      }
      variants {
        docs {
          id
          priceInEUR
          title
          options {
            id
            label
            value
          }
          inventory
        }
      }
      variantTypes {
        id
        label
        name
        options {
          docs {
            id
            label
            value
          }
        }
      }

      categories {
        id
        slug
        title
      }

      meta{
        title
        description
      }
    }
  }
}
