query ProductsByCategory($locale: LocaleInputType!, $categoryId: JSON!) {
  Products(
    locale: $locale
    limit: 10000
    where: { categories: { equals: $categoryId } }
  ) {
    docs {
      id
      title
      slug
      priceInEUR
      enableVariants
      description
      inventory
      gallery {
        id
        url
        thumbnailURL
        width
        height
        alt
      }
      variants {
        docs {
          id
          priceInEUR
          title
          options {
            id
            label
            value
          }
          inventory
        }
      }
      variantTypes {
        id
        label
        name
        options {
          docs {
            id
            label
            value
          }
        }
      }

      categories {
        id
        slug
        title
      }

      meta {
        title
        description
      }
    }

    totalDocs
  }
}
